version: '3'

services:
  app:
    container_name: app
    command: python3 -m http.server 5000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    volumes:
      - .:/app