import unittest
from src.linked_list import LinkedList, OutOfBoundsException


class TestLinkedList(unittest.TestCase):
    def test_linked_list(self):
        ll = LinkedList()
        assert(ll.head is None)
        assert(ll.tail is None)
        assert(ll.toList() == [])
        ll.append(1)
        assert(ll.head == 1)
        assert(ll.tail == 1)
        assert(len(ll) == 1)
        assert(ll.getValueAt(0) == 1)
        assert(ll.toList() == [1])
        ll.append(2)
        assert(ll.head == 1)
        assert(ll.tail == 2)
        assert(len(ll) == 2)
        assert(ll.toList() == [1, 2])
        assert(ll.getValueAt(0) == 1)
        assert(ll.getValueAt(1) == 2)
        ll.append(3)
        assert(ll.head == 1)
        assert(ll.tail == 3)
        assert(len(ll) == 3)
        assert(ll.toList() == [1, 2, 3])
        assert(ll.getValueAt(0) == 1)
        assert(ll.getValueAt(1) == 2)
        assert(ll.getValueAt(2) == 3)
        ll.insert(0)
        assert(ll.head == 0)
        assert(ll.tail == 3)
        assert(len(ll) == 4)
        assert(ll.toList() == [0, 1, 2, 3])
        assert(ll.getValueAt(0) == 0)
        assert(ll.getValueAt(1) == 1)
        assert(ll.getValueAt(2) == 2)
        assert(ll.getValueAt(3) == 3)
        ll.insert(-1)
        assert(ll.toList() == [-1, 0, 1, 2, 3])
        assert(ll.getValueAt(0) == -1)
        assert(ll.getValueAt(1) == 0)
        assert(ll.getValueAt(2) == 1)
        assert(ll.getValueAt(3) == 2)
        assert(ll.getValueAt(4) == 3)
        v = ll.removeFirst()
        assert(v == -1)
        assert(ll.toList() == [0, 1, 2, 3])
        assert(ll.getValueAt(0) == 0)
        assert(ll.getValueAt(1) == 1)
        assert(ll.getValueAt(2) == 2)
        assert(ll.getValueAt(3) == 3)
        v = ll.removeFirst()
        assert(v == 0)
        assert(ll.toList() == [1, 2, 3])
        assert(ll.getValueAt(0) == 1)
        assert(ll.getValueAt(1) == 2)
        assert(ll.getValueAt(2) == 3)
        v = ll.removeFirst()
        assert(v == 1)
        assert(ll.toList() == [2, 3])
        assert(ll.getValueAt(0) == 2)
        assert(ll.getValueAt(1) == 3)
        v = ll.removeFirst()
        assert(v == 2)
        assert(ll.toList() == [3])
        assert(ll.getValueAt(0) == 3)
        v = ll.removeFirst()
        assert(v == 3)
        assert(ll.toList() == [])
        assert(len(ll) == 0)
    
    def test_raises(self):
        ll = LinkedList()
        with self.assertRaises(OutOfBoundsException):
            ll.getValueAt(50)